### ISSUE TITLE
Enable travis CI for Sushi project

### ISSUE THREAD

**Issue by leonwanghui** [opensds/nbp#110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
In [Hotpot](https://github.com/opensds/opensds) project we enabled travis CI service to build, deploy and test this project. I think Sushi project should also enable this service to test the code automatically.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Hi @stmcginnis , could you take a look? Thanks!

**Comment by stmcginnis** [comment]
Doesn't sushi already have this?

https://github.com/opensds/nbp/blob/master/.travis.yml

**Comment by leonwanghui** [comment]
Yes `travis.yml` was created, but I don't know why the ci checking doesn't work every time we push a PR : (

**Comment by leonwanghui** [comment]
Hi @stmcginnis , it seems that the travis CI still not work : (

**Comment by leonwanghui** [comment]
I think it works now, aha!

**Comment by xing-yang** [comment]
@leonwanghui Yes, I noticed that yesterday when my PR triggered the CI:).
