### ISSUE TITLE
PVC was bound to PV when the volume was in error state

### ISSUE THREAD

**Issue by xing-yang** [opensds/nbp#127]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
While testing the latest code in nbp development branch, ran into the following bug. I created a PVC.  It shows that it was bound to a PV.  However when checking the volume in OpenSDS dashboard, this volume was actually in error status.

Searched the osdslet logs, it showed that the problem was because there is no default profile created.

This may be a bug in Hotpot, but since I found it by running CSI plugin, I opened the issue here.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
kubectl create -f examples/kubernetes/pvc_sc.yaml

root@ubuntu:~/gopath/src/github.com/opensds/nbp/csi/server/examples/kubernetes# kubectl get pvc
NAME         STATUS   VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS           AGE
opensdspvc   Bound    pvc-1ab00c49b60411e8   1Gi        RWO            csi-sc-opensdsplugin   5s

root@ubuntu:~/gopath/src/github.com/opensds/nbp/csi/server/examples/kubernetes# kubectl get pv
NAME                   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                STORAGECLASS           REASON   AGE
pvc-1ab00c49b60411e8   1Gi        RWO            Delete           Bound    default/opensdspvc   csi-sc-opensdsplugin            49s

vi osdslet.ubuntu.root.log.ERROR.20180908-175346.20945

E0908 17:53:46.809628   20945 controller.go:103] Get profile failed: No default profile in db.
E0908 17:53:46.810523   20945 volume.go:88] Marshal volume created result failed: No default profile in db.
E0908 17:53:47.022767   20945 db.go:123] Only the status of volume is available, attachment can be created
E0908 17:53:47.022835   20945 volume.go:329] Create volume attachment failed: Only the status of volume is available, attachment can be created

**Anything else we need to know?**:

**Environment**:
- NBP version: Latest development branch
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools: opensds-installer
- Others:

**Comment by wisererik** [comment]
Thanks Xing, IMO, CSI plugin should check the status of volume. OpenSDS Controller also should check if the profile exists.

**Comment by xing-yang** [comment]
I think this is fixed now.
