### ISSUE TITLE
ListSnapshots needs to be fixed

### ISSUE THREAD

**Issue by xing-yang** [opensds/nbp#128]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
ListSnapshots is not implemented according to the CSI spec.  It needs to take into account of the input parameters:
message ListSnapshotsRequest {
  int32 max_entries = 1;
  string starting_token = 2;
  string source_volume_id = 3;
  string snapshot_id = 4;
}

It also needs to set next_token in the response:

message ListSnapshotsResponse {
  message Entry {
    Snapshot snapshot = 1;
  }

  repeated Entry entries = 1;

  string next_token = 2;
}

Take a look of this driver as example: https://github.com/kubernetes-csi/drivers/blob/master/pkg/hostpath/controllerserver.go#L266

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wisererik** [comment]
It's a feature of pagination. I think ListVolumes also has the same problem.

**Comment by xing-yang** [comment]
Fixed.
