### ISSUE TITLE
Move client and connector from project opensds to project nbp.

### ISSUE THREAD

**Issue by lasshpanzer** [opensds/nbp#180]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind feature

**What happened**:
Currently the connector and client is in project opensds, nbp needs to import it as third party open source which is currently under project nbp vendor dictionary, resulting in serious coupling.
**What you expected to happen**:
Move client and connector from project opensds to project nbp, aim to decouple the opensds and nbp.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
I get your point, but actually hotpot project has dependency on `connector` either, and it's very odd if sushi is imported by hotpot.

**Comment by xing-yang** [comment]
@lasshpanzer We have discussed about this and decided not to move it.  Can you close this?
