### ISSUE TITLE
fs_type should be retrieved from VolumeCapability in CSI

### ISSUE THREAD

**Issue by wisererik** [opensds/nbp#210]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:

In `CreateVolume` method, CSI plugin gets `fs_type` from parameters of `CreateVolumeRequest`, this doesn't obey the CSI specification correctly.

**What you expected to happen**:

Retrieving fs_type from `VolumeCapablities` of `CreateVolumeRequest`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wisererik** [comment]
@jackhaibo please take a look of this issue.

**Comment by jackhaibo** [comment]
@wisererik Is `fs_type==“ext4”` in `VolumeCapablities` the default? Or can it be specified? I did not find a detailed explanation in the kubernetes official website documentation. The other `csi-driver` implementations are as follows:
```
fsType := "ext4"
if mnt := volumeCapability.GetMount(); mnt != nil {
	if mnt.FsType != "" {
		fsType = mnt.FsType
	}
}
```

**Comment by wisererik** [comment]
yes, u can use ext4 as a default. please see detail in csi spec. like the following:
```
// Indicate that the volume will be accessed via the filesystem API.
  message MountVolume {
    // The filesystem type. This field is OPTIONAL.
    // An empty string is equal to an unspecified field value.
    string fs_type = 1;

    // The mount options that can be used for the volume. This field is
    // OPTIONAL. `mount_flags` MAY contain sensitive information.
    // Therefore, the CO and the Plugin MUST NOT leak this information
    // to untrusted entities. The total size of this repeated field
    // SHALL NOT exceed 4 KiB.
    repeated string mount_flags = 2;
  }

  // Specify how a volume can be accessed.
  message AccessMode {
    enum Mode {
      UNKNOWN = 0;

      // Can only be published once as read/write on a single node, at
      // any given time.
      SINGLE_NODE_WRITER = 1;

      // Can only be published once as readonly on a single node, at
      // any given time.
      SINGLE_NODE_READER_ONLY = 2;

      // Can be published as readonly at multiple nodes simultaneously.
      MULTI_NODE_READER_ONLY = 3;

      // Can be published at multiple nodes simultaneously. Only one of
      // the node can be used as read/write. The rest will be readonly.
      MULTI_NODE_SINGLE_WRITER = 4;

      // Can be published as read/write at multiple nodes
      // simultaneously.
      MULTI_NODE_MULTI_WRITER = 5;
    }

    // This field is REQUIRED.
    Mode mode = 1;
  }
```

**Comment by jackhaibo** [comment]
Already use `ext4` as a default, please see [https://github.com/opensds/nbp/pull/218]

**Comment by skdwriting** [comment]
@wisererik , can we close this issue?

**Comment by wisererik** [comment]
yes, it's solved, will close it.
