### ISSUE TITLE
ServiceInstances can not change status from false

### ISSUE THREAD

**Issue by syutadeveloper** [opensds/nbp#213]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

I build Kubernetes and run service catalog.
Also I run service broker with OpenSDS.
But created service instances always has status false.

**What you expected to happen**:

Kubernetes can use service instances and service bindings.

**How to reproduce it (as minimally and precisely as possible)**:

I have Kubernetes cluster. 1 master, 2 nodes. There are on the KVM.
Platform is Kubic which is distributed by openSUSE for to build Kubernetes.
I have one LVM volume on master.
OpenSDS run on master. and setup dock above LVM.(OpenSDS recognized above LVM is pool.)
When I created service instance, OpenSDS created volume for pvc.
but, that is all.

I referenced at https://github.com/opensds/opensds/wiki/OpenSDS-Installation-with-Kubernetes-Service-Catalog

I adjusted:

service catalog:
 I turn off health check, because that is failed often.

service broker:
I replace spec.spec.volumes.hostpath.path to /var/lib/ca-certificates in broker-deployment.yaml

**Anything else we need to know?**:

**Environment**:
- NBP version: helm install before few days.

- OS (e.g. from /etc/os-release): 
openSUSE Tumbleweed Kubic

- Kernel (e.g. `uname -a`):
 Linux linux-36zj 5.0.5-1-default #1 SMP Wed Mar 27 11:22:35 UTC 2019 (0fb0b14) x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:
log attached.
[catalog-catalog-apiserver.log](https://github.com/opensds/nbp/files/3085460/catalog-catalog-apiserver.log)
[catalog-catalog-controller-manager.log](https://github.com/opensds/nbp/files/3085461/catalog-catalog-controller-manager.log)
[service-broker-service-broker.log](https://github.com/opensds/nbp/files/3085462/service-broker-service-broker.log)

What am I wrong?

**Comment by leonwanghui** [comment]
Hi @syutadeveloper, I think this doc is out-of-date for a while, I updated the docs [https://github.com/opensds/opensds/wiki/OpenSDS-Installation-with-Kubernetes-Service-Catalog](https://github.com/opensds/opensds/wiki/OpenSDS-Installation-with-Kubernetes-Service-Catalog) but I still need to retest if it's working.

**Comment by syutadeveloper** [comment]
@leonwanghui Thank you! I try again and I can go next step.(Status set to True.) Is the point namespace of service-broker? Anyway I close this issue and continue.
