### ISSUE TITLE
OpenSDS storage platform not getting removed for VMWare

### ISSUE THREAD

**Issue by shanu04** [opensds/nbp#256]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
OpenSDS storage platform not getting removed for vmware.
**What you expected to happen**:
Should perform remove operation on storage platform.

**How to reproduce it (as minimally and precisely as possible)**:
Step1 Open OpenSDS Storgae plugin from Home/administration
Step2 Select the storage platform you want to remove.

Showing "no actions available".

**Anything else we need to know?**:
Its not consistent. Happening for 192.168.20.125 opensds storage.
**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NajmudheenCT** [comment]
Not reproducable , delete storage platform works . closing this issue. Please open if noticed again
