### ISSUE TITLE
[VMWare/vRO] Analysis of vRo

### ISSUE THREAD

**Issue by PravinRanjan10** [opensds/nbp#260]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PravinRanjan10** [comment]
Duplicate of #234

**Comment by himanshuvar** [comment]
@PravinRanjan10 How #234 & #260 duplicates of each other?

**Comment by PravinRanjan10** [comment]
@himanshuvar It's laready closed.  I was just checking the various options just for TEST.
