### ISSUE TITLE
CSI plugin should be updated for 0.2.0

### ISSUE THREAD

**Issue by xing-yang** [opensds/nbp#81]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: CSI v0.2.0 is cut

**What you expected to happen**: CSI plugin should be updated to support 0.2.0.

**How to reproduce it (as minimally and precisely as possible)**: Test with CSI 0.2.0 and latest K8S code (1.10).

**Anything else we need to know?**: See this PR for example: https://github.com/kubernetes-csi/drivers/pull/56

**Environment**:
- NBP version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leonwanghui** [comment]
Yeah, I think we should target it at Aruba release.

**Comment by xing-yang** [comment]
This is addressed now.
